[build]
  publish = "public/"
  command = "npm run build"

[context.branch-deploy]
  publish = "public/"
  command = "npm run build"

[context.2020-fall]
  publish = "public/"
  command = "npm run build"

