[build]
  publish = "build/"
  command = "npm build"

[context.branch-deploy]
  publish = "public/"
  command = "gatsby develop"

[context.xue-card]
  publish = "public/"
  command = "gatsby develop"
  base = "xue-card"
