[build]
  publish = "build/"
  command = "yarn build"

[context.branch-deploy]
  publish = "public/"
  command = "npm run develop"

[context.xue-card]
  publish = "public/"
  command = "npm run develop"

