import Card from "./card";

const cardArr: Array<Card> = [
  {
    title: 'Big Data Workshop',
    description: 'Learn about Big Data and Pipelining!',
    time: 'Sat Oct 3nd, 10-11am CST',
    difficulty: 0,
    level: 'No experience necessary :)',
    codeLink: 'https://github.com/VandyHacks/BigDataWorkshop',
    slidesLink: 'https://docs.google.com/presentation/d/1OMv4DPrLUQ3TVVVN7hgPgv0G_hVqQoR6-buZxnGDOsg/edit?usp=sharing',
    dependency: 'Python 3, Pip 3',
    dependencyLink: "",
    visible: true,
    vidLink: 'https://youtu.be/txRjZvOAMnc',
  },
  {
    title: 'Google Cloud API',
    description: 'Learn how to recognize image text and translate text using Google Cloud APIs.',
    time: 'Sat Oct 3nd, 11am-12pm CST',
    difficulty: 0,
    level: 'No experience necessary :)',
    codeLink: 'https://github.com/VandyHacks/GoogleCloudWorkshop',
    slidesLink: 'https://docs.google.com/presentation/d/1HVPxRWb3HA2-9NvKapEZr2OWg5pGyoe4ZekhRAbehc4/edit?usp=sharing',
    dependency: 'Google Colab',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://youtu.be/D_H4vchrSn8',
  },
  {
    title: 'Neural Networks',
    description: 'Learn how to apply Deep Learning to your own projects!',
    time: 'Sat Oct 3nd, 8-9am CST',
    difficulty: 0,
    level: 'No experience necessary :)',
    codeLink: 'https://github.com/VandyHacks/NeuralNetworksWorkshop',
    slidesLink: 'https://docs.google.com/presentation/u/2/d/12HoHZ7RrKxewx9B0Ag8aJsFUzwKsk084JVNBA5w8vmI/edit#slide=id.p',
    dependency: 'Google Colab',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://youtu.be/Yue_yX5k-Hc',
  },
  {
    title: 'Open Source',
    description: 'Learn about Open Source through the Chrome Dino Game!',
    time: 'Fri Oct 2nd, 10-11pm CST',
    difficulty: 0,
    level: 'No experience necessary :)',
    codeLink: 'https://github.com/VandyHacks/Opensaurus-Rex-HackPack',
    slidesLink: 'https://tinyurl.com/vmpscj5',
    dependency: 'Git, GitHub, VSCode',
    dependencyLink: "https://tinyurl.com/uml7nzl",
    visible: true,
    vidLink: 'https://youtu.be/0fkE7Awceig',
  },
  {
    title: 'React Native',
    description: 'Learn about React Native by making a Todo app!',
    time: 'Sat Oct 3nd, 9-10am CST',
    difficulty: 1,
    level: 'Basic React experience needed',
    codeLink: 'https://github.com/VandyHacks/ReactNativeWorkshop',
    slidesLink: 'https://docs.google.com/presentation/d/1XfVOYSWAFPlP-QP_0b6b5QjV6OIBvjCnrIeJi-5O8pE/edit#slide=id.p',
    dependency: 'React, IDE of choice',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://youtu.be/e2JHoda3RZU',
  },
  {
    title: 'SlackBot',
    description: 'Learn how APIs, App Registration, Permissions, and Deployment work with SlackBots!',
    time: 'Fri Oct 2nd, 11pm-12am',
    difficulty: 1,
    level: 'Some JavaScript experience encouraged',
    codeLink: 'https://github.com/VandyHacks/SlackBotWorkshop',
    slidesLink: 'https://tinyurl.com/ydxfhgkf',
    dependency: 'Git, GitHub, VSCode',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://youtu.be/12lSoyqgSxw',
  },
  {
    title: 'Full Stack with Angular',
    description: 'Learn how to create a basic web application in Angular, using Firebase for data storage and authentication!',
    time: 'Fri Oct 2nd, 9-10pm',
    difficulty: 1,
    level: 'Some experience with web development encouraged',
    codeLink: 'https://github.com/VandyHacks/AngularFirebaseWorkshop',
    slidesLink: '',
    dependency: 'Node, NPM, Angular-CLI',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://youtu.be/peKt6tRog60',
  }, 
  { title: 'Intro To HTML and CSS',
    description: 'Learn how to make an instagram clone through HTML and CSS!',
    time: 'Fri Oct 2nd, 11pm-12am',
    difficulty: 1,
    level: 'No experience necessary :)',
    codeLink: '',
    slidesLink: '',
    dependency: 'Nothing!',
    dependencyLink: '',
    visible: true,
    vidLink: 'https://www.youtube.com/watch?v=UERiW69QqG4',
  }
];

export default cardArr;
